synthetic-package: false

arb-dir: lib/src/l10n/arb
template-arb-file: app_de.arb
output-dir: lib/src/l10n/generated
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.json